CourseTrigger/force-app/main/default/objects/Course__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of the Course</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

CourseTrigger/force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <description>Lessons</description>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CourseTrigger/force-app/main/default/objects/Lesson__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of Lesson</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

CourseTrigger/force-app/main/default/objects/Subject__c/fields/Number_of_Lessons__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Lessons__c</fullName>
    <description>Number of Lessons</description>
    <label>Number of Lessons</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DXFirst/force-app/main/default/classes/CreateLessons.cls
/**
 * Created by DmytroPinchuk on 19.08.2019.
 */

public with sharing class CreateLessons {
    public void formCourseAndLessons(List<sObject> newCourses) {
        Set<Id> subjectIds = new Set<Id>();
        for (Course__c course : (List<Course__c>) newCourses) {
            subjectIds.add(course.Subject__c);
        }
        Map<Id, Subject__c> subjectsById = new Map<Id, Subject__c>([
                SELECT Id, Number_Of_Lessons__c
                FROM Subject__c
                WHERE Id IN :subjectIds
        ]);
        insertLessons(newCourses, subjectsById);
    }

    public static void insertLessons(List<sObject> newCourses, Map<Id, Subject__c> subjectsById) {
        List<Lesson__c> lessons = new List<Lesson__c>();
        for (Course__c course : (List<Course__c>) newCourses) {
            Decimal lessonsDecimal = subjectsById.get(course.Subject__c).Number_Of_Lessons__c;
            for (Integer i = 0; i < lessonsDecimal; i++) {
                Lesson__c lesson = new Lesson__c();
                lesson.Course__c = course.Id;
                Date courseDate = course.Start_Date__c;
                lesson.Date__c = courseDate.addDays(i);
                lessons.add(lesson);
            }
        }
        insert lessons;
    }
}